{"ip": "2600:8801:685:5001:4c60:a1ae:f32c:9c47", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 2, in <module>\n    myCode = int(input('what is the code? '))\nValueError: invalid literal for int() with base 10: ''\n", "LastIsEmpty": true, "ErrorType": "ValueError", "CoverageInfo": [7, 5, 2, 0, 22, "3-7"], "CorrectInputs": [[["1234", "1111"], 1492904521]], "BadInput": [""], "UniqueId": "c22785e3-35a4-4701-931b-b5cc38fa14cf_0", "TimeStamp": 1492904384}