{"ip": "176.119.118.128", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 23, in <module>\n    sum[i][j] = ((a[i - 1+g][j]) + (a[i +1-g+c][j]) + (a[i][j-1+h]) + (a[i][j+1-h+d]))\nIndexError: list index out of range\n", "LastIsEmpty": false, "ErrorType": "IndexError", "CoverageInfo": [26, 9, 24, 4, 58, "17-22,", "24-27,", "11->24,", "12->11,", "14->19,", "16->17"], "CorrectInputs": [[["1", "end"], 1513565154]], "BadInput": ["1 1", "end"], "UniqueId": "c286d0ba-9f23-4900-956f-052bc315b3e6_0", "TimeStamp": 1513565214}