{"ip": "198.169.140.30", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 3, in <module>\n    c=(int(input(\"number\")))\nValueError: invalid literal for int() with base 10: '7.5'\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [5, 2, 2, 1, 57, "4-5,", "2->exit"], "CorrectInputs": [[["Celsius", "87"], 1489804305]], "BadInput": ["Celsius", "7.5"], "UniqueId": "c227b62d-3919-4040-e350-1eb7e8d1d0b3_1", "TimeStamp": 1489804237}