{"ip": "186.211.178.114", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 6, in <module>\n    linha.append(int(input()))\nValueError: invalid literal for int() with base 10: '0,1,0,0,1,0,0,1,0'\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [13, 7, 10, 2, 35, "7-13,", "3->8,", "5->7"], "CorrectInputs": [[["0", "1", "0", "0", "1", "1", "0", "1", "0"], 1510294457]], "BadInput": ["0,1,0,0,1,0,0,1,0"], "UniqueId": "c2100a18-fce7-4bd3-d996-c2a809d6144d_0", "TimeStamp": 1510294324}