{"ip": "4.28.70.34", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 23, in <module>\n    hanoi(number, start, goal, work)\n  File \"temp2017.py\", line 20, in hanoi\n    hanoi(n-1, work, goal, start)\n  File \"temp2017.py\", line 14, in hanoi\n    goal.append(start.pop())\nIndexError: pop from empty list\n", "LastIsEmpty": false, "ErrorType": "IndexError", "CoverageInfo": [16, 1, 6, 1, 91, "24,", "22->exit"], "CorrectInputs": [[["4 15"], 1505777610]], "BadInput": ["4 6"], "UniqueId": "c2ad8458-a21f-4310-a5bd-df5eec9660e6_3", "TimeStamp": 1505777773}