{"ip": "189.35.185.52", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 2, in <module>\n    n1,n2,n3=elementos.split(' ')\nValueError: too many values to unpack (expected 3)\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [18, 16, 10, 0, 7, "3-21"], "CorrectInputs": [[["6.0 6.0 10.0"], 1508386060], [["6.0 6.0 6.0"], 1508386096], [["5.0 7.0 2.0"], 1508386130]], "BadInput": [" 6.0 6.0 6.0"], "UniqueId": "c2508b9a-2e06-419d-fe8a-7fc840503dbd_3", "TimeStamp": 1508386080}