{"ip": "198.169.140.30", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 5, in <module>\n    print(\"number is \" + str(celsius))\nNameError: name 'celsius' is not defined\n", "LastIsEmpty": false, "ErrorType": "NameError", "CoverageInfo": [5, 0, 2, 1, 86, "2->exit"], "CorrectInputs": [[["celsius"], 1489804118]], "BadInput": ["Celsius", "90"], "UniqueId": "c227b62d-3919-4040-e350-1eb7e8d1d0b3_0", "TimeStamp": 1489804156}