{"ip": "2a02:6b8:b010:7016::24", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 1, in <module>\n    n, m = (int(i) for i in input().split())\nValueError: not enough values to unpack (expected 2, got 0)\n", "LastIsEmpty": true, "ErrorType": "ValueError", "CoverageInfo": [38, 37, 40, 1, 3, "3-46,", "1->3"], "CorrectInputs": [[["3 3", "1", "3", "4", "2", "4", "1"], 1493484969]], "BadInput": [""], "UniqueId": "c2b0e5f7-1b6f-4a43-ef0c-a3bdea99781d_0", "TimeStamp": 1493484655}