{"ip": "4.28.70.34", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 24, in <module>\n    hanoi(number, start, goal, work)\n  File \"temp2017.py\", line 21, in hanoi\n    hanoi(n-1, work, goal, start)\n  File \"temp2017.py\", line 15, in hanoi\n    goal.append(start.pop())\nIndexError: pop from empty list\n", "LastIsEmpty": false, "ErrorType": "IndexError", "CoverageInfo": [20, 4, 6, 1, 81, "25-28,", "23->exit"], "CorrectInputs": [[["3 4"], 1505776823]], "BadInput": ["4 6"], "UniqueId": "c2ad8458-a21f-4310-a5bd-df5eec9660e6_0", "TimeStamp": 1505776846}