{"ip": "200.17.112.121", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 6, in <module>\n    elif nome.uper() not in funcionarios_cadastrados:\nAttributeError: 'str' object has no attribute 'uper'\n", "LastIsEmpty": false, "ErrorType": "AttributeError", "CoverageInfo": [8, 4, 4, 2, 50, "5,", "7-9,", "4->5,", "6->7"], "CorrectInputs": [[["caio"], 1505158959]], "BadInput": ["pedro"], "UniqueId": "c2ca9d87-1823-4528-a0fe-b2519d66dfaa_0", "TimeStamp": 1505158970}